services:
  - type: web
    name: inkibateurdz
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server/index.cjs
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
